"""Source-specific Scientific Document V2 implementation."""

from .contracts import (
    DOCUMENT_ADAPTER_VERSION,
    DOCUMENT_CONTRACT_VERSION,
    DOCUMENT_SCHEMA_VERSION,
    DocumentComparison,
    DocumentEdge,
    DocumentEdgeType,
    DocumentEntity,
    DocumentEntityType,
    DocumentFactAuthority,
    DocumentFamily,
    DocumentLayoutBlockType,
    DocumentOcrStatus,
    DocumentParserProviderStatus,
    DocumentPublication,
    DocumentRetrievalUnit,
    DocumentScope,
    DocumentSourceKind,
    DocumentTombstone,
    DocumentVersion,
)
from .runtime_v2 import (
    DOCUMENT_SOURCE_DEFAULT_ENGINE,
    DOCUMENT_SOURCE_RUNTIME_VERSION,
    DocumentSourceRuntimeError,
    DocumentSourceRuntimeV2,
)

__all__ = [
    "DOCUMENT_ADAPTER_VERSION",
    "DOCUMENT_CONTRACT_VERSION",
    "DOCUMENT_SCHEMA_VERSION",
    "DOCUMENT_SOURCE_DEFAULT_ENGINE",
    "DOCUMENT_SOURCE_RUNTIME_VERSION",
    "DocumentComparison",
    "DocumentEdge",
    "DocumentEdgeType",
    "DocumentEntity",
    "DocumentEntityType",
    "DocumentFamily",
    "DocumentFactAuthority",
    "DocumentLayoutBlockType",
    "DocumentOcrStatus",
    "DocumentParserProviderStatus",
    "DocumentPublication",
    "DocumentRetrievalUnit",
    "DocumentScope",
    "DocumentSourceKind",
    "DocumentSourceRuntimeError",
    "DocumentSourceRuntimeV2",
    "DocumentTombstone",
    "DocumentVersion",
]
