"""Stable public contract for Code Source retrieval."""

from importlib import import_module
from typing import TYPE_CHECKING, Any

from .contracts import (
    CodeCalibratedRelevance,
    CodeCalibratedScore,
    CodeCalibrationStatus,
    CodeCandidateRole,
    CodeChannelCompleteNoMatch,
    CodeChannelCompletePruned,
    CodeChannelCompleteWithHits,
    CodeChannelDisabled,
    CodeChannelError,
    CodeChannelErrorKind,
    CodeChannelFailure,
    CodeChannelOutcome,
    CodeChannelOutcomeStatus,
    CodeChannelRank,
    CodeChannelScore,
    CodeChannelTimeout,
    CodeChannelUnavailable,
    CodeContextBlock,
    CodeDerivation,
    CodeFactStatus,
    CodeFallback,
    CodeFallbackFailed,
    CodeFallbackFailure,
    CodeFallbackNotUsed,
    CodeFallbackStatus,
    CodeFallbackSucceeded,
    CodeQueryProfile,
    CodeRelationHop,
    CodeRelationLocator,
    CodeRelationNode,
    CodeRelationPath,
    CodeRelationType,
    CodeRetrievalBudget,
    CodeRetrievalCandidate,
    CodeRetrievalChannel,
    CodeReviewStatus,
    CodeSourceError,
    CodeSourceResult,
    CodeSourceStatus,
    CodeTask,
    CodeTraversalDirection,
    CodeUncalibratedScore,
    CodeVersionAlignment,
)
from .graph_v2 import (
    CODE_EDGE_REGISTRY,
    CODE_EDGE_SPECS,
    EDGE_REGISTRY,
    CodeEdgeDerivationLayer,
    CodeEdgeDirection,
    CodeEdgeGenerationRequirement,
    CodeEdgeInverse,
    CodeEdgeOwner,
    CodeEdgeReviewRequirement,
    CodeEdgeSpec,
    CodeEdgeVersionRequirement,
    CodeGraphEntity,
    CodeGraphEntityType,
    CodeSymbolKind,
    CodeUnresolvedAggregate,
    CodeUnresolvedDiagnostic,
    CodeUnresolvedDiagnostics,
    CodeUnresolvedLanguageModuleAggregate,
    CodeUnresolvedReason,
    get_edge_spec,
    registered_edge_type,
    require_registered_edge_types,
    summarize_unresolved_diagnostics,
    validate_edge_assertion,
)
from .schema import CODE_V2_SCHEMA
from .store import CodeV2StoreMixin

if TYPE_CHECKING:
    from .dense_v2 import (
        CodeDenseError,
        CodeDenseHitTrace,
        CodeDenseProfilePublisher,
        CodeDensePublicationError,
        CodeDensePublicationResult,
        CodeDenseRetriever,
        CodeDenseSearchResult,
        CodeDenseStore,
        CodeDenseTrace,
        CodeDenseUnavailableError,
        CodeHybridHitTrace,
        CodeHybridSearchResult,
        CodeHybridTrace,
        CodeHybridV2Retriever,
        DenseModelCandidate,
        resolve_code_embedding_profile,
    )
    from .dual_write import (
        CodeDualWriteCoordinator,
        CodeDualWriteResult,
        CodeDualWriteStore,
    )
    from .embedding_v2 import (
        CodeEmbeddingError,
        CodeEmbeddingIndexer,
        CodeEmbeddingIndexResult,
        CodeEmbeddingStore,
        CodeEmbeddingTrace,
        EmbeddingBatchError,
        EmbeddingBatchResult,
        EmbeddingDimensionError,
        EmbeddingProfile,
        EmbeddingProvenance,
        EmbeddingProvider,
        EmbeddingProviderUnavailableError,
        LocalHashCodeEmbeddingProvider,
        embedding_cache_key,
    )
    from .graph_publication_v2 import (
        CODE_GRAPH_PUBLICATION_VERSION,
        CodeGraphProfilePublisher,
        CodeGraphPublicationResult,
        CodeGraphPublicationStore,
    )
    from .graph_retrieval_v2 import (
        CodeGraphRetriever,
        CodeGraphV2Retriever,
        CodeTypedGraphRetriever,
        GraphAdjacencyProvider,
        GraphEdge,
        GraphNode,
        GraphPublication,
        GraphTraversalCandidate,
        GraphTraversalPath,
        GraphTraversalRequest,
        GraphTraversalResult,
        GraphTraversalStatus,
        GraphTraversalTrace,
        SQLiteGraphAdjacencyProvider,
        fuse_graph_candidates,
    )
    from .query_profile_v2 import (
        CodeAdaptiveK,
        CodeCalibrationPolicy,
        CodeCandidateReranker,
        CodeContextTemplate,
        CodeHistoryExpansionHook,
        CodeMissingRolePolicy,
        CodeOptionalHookResult,
        CodeOptionalHookStatus,
        CodePipelineStageStatus,
        CodePipelineTraceEvent,
        CodeProfiledRetriever,
        CodeQueryProfileV2,
        CodeQueryRewrite,
        CodeRewritePolicy,
        CodeSourceFusionPipeline,
        CodeSourceFusionSearchResult,
        CodeSourceFusionTrace,
        CodeTestValidationExpansionHook,
        ResolvedCodeQueryProfile,
        get_code_query_profile,
        infer_code_task,
        resolve_code_query_profile,
        rewrite_code_query,
    )
    from .rerank_v2 import (
        CalibrationApplication,
        CalibrationArtifact,
        CalibrationArtifactMismatchError,
        CalibrationBin,
        CalibrationSample,
        CodeRerankedRetriever,
        CodeRerankedSearchResult,
        CodeRerankTrace,
        DeterministicCodeReranker,
        EvidenceCard,
        FeatureVector,
        RerankDeadlineExceeded,
        RerankDecision,
        RerankModelCandidate,
        apply_calibration,
        fit_calibration,
    )
    from .retrieval_v2 import (
        CodeChannelHitTrace,
        CodeExactSparseRetriever,
        CodeExactSparseSearchResult,
        CodeExactSparseTrace,
        CodeLocatorKind,
        CodeLocatorTrace,
        CodeV2RetrievalStore,
    )
    from .shadow import (
        CodeShadowError,
        CodeShadowFailure,
        CodeShadowObservation,
        CodeShadowRankDelta,
        CodeShadowRunner,
        CodeShadowStage,
        CodeSourceRetrieverProtocol,
    )
    from .v1_adapter import (
        CodeSourceRetrieverV1Adapter,
        LegacyCodeResponseError,
    )

_LAZY_EXPORTS = {
    "CODE_QUERY_PROFILES": (".query_profile_v2", "CODE_QUERY_PROFILES"),
    "CODE_QUERY_PROFILE_REGISTRY": (
        ".query_profile_v2",
        "CODE_QUERY_PROFILE_REGISTRY",
    ),
    "CODE_QUERY_PROFILE_REGISTRY_BY_KEY": (
        ".query_profile_v2",
        "CODE_QUERY_PROFILE_REGISTRY_BY_KEY",
    ),
    "PIPELINE_VERSION": (".query_profile_v2", "PIPELINE_VERSION"),
    "PROFILE_REGISTRY_VERSION": (".query_profile_v2", "PROFILE_REGISTRY_VERSION"),
    "REWRITE_VERSION": (".query_profile_v2", "REWRITE_VERSION"),
    "CodeAdaptiveK": (".query_profile_v2", "CodeAdaptiveK"),
    "CodeCalibrationPolicy": (".query_profile_v2", "CodeCalibrationPolicy"),
    "CodeCandidateReranker": (".query_profile_v2", "CodeCandidateReranker"),
    "CodeContextTemplate": (".query_profile_v2", "CodeContextTemplate"),
    "CodeHistoryExpansionHook": (".query_profile_v2", "CodeHistoryExpansionHook"),
    "CodeMissingRolePolicy": (".query_profile_v2", "CodeMissingRolePolicy"),
    "CodeOptionalHookResult": (".query_profile_v2", "CodeOptionalHookResult"),
    "CodeOptionalHookStatus": (".query_profile_v2", "CodeOptionalHookStatus"),
    "CodePipelineStageStatus": (".query_profile_v2", "CodePipelineStageStatus"),
    "CodePipelineTraceEvent": (".query_profile_v2", "CodePipelineTraceEvent"),
    "CodeProfiledRetriever": (".query_profile_v2", "CodeProfiledRetriever"),
    "CodeQueryProfileV2": (".query_profile_v2", "CodeQueryProfileV2"),
    "CodeQueryRewrite": (".query_profile_v2", "CodeQueryRewrite"),
    "CodeRewritePolicy": (".query_profile_v2", "CodeRewritePolicy"),
    "CodeSourceFusionPipeline": (".query_profile_v2", "CodeSourceFusionPipeline"),
    "CodeSourceFusionSearchResult": (
        ".query_profile_v2",
        "CodeSourceFusionSearchResult",
    ),
    "CodeSourceFusionTrace": (".query_profile_v2", "CodeSourceFusionTrace"),
    "CodeTestValidationExpansionHook": (
        ".query_profile_v2",
        "CodeTestValidationExpansionHook",
    ),
    "ResolvedCodeQueryProfile": (".query_profile_v2", "ResolvedCodeQueryProfile"),
    "get_code_query_profile": (".query_profile_v2", "get_code_query_profile"),
    "infer_code_task": (".query_profile_v2", "infer_code_task"),
    "resolve_code_query_profile": (
        ".query_profile_v2",
        "resolve_code_query_profile",
    ),
    "rewrite_code_query": (".query_profile_v2", "rewrite_code_query"),
    "CodeDenseError": (".dense_v2", "CodeDenseError"),
    "CodeDenseHitTrace": (".dense_v2", "CodeDenseHitTrace"),
    "CodeDenseProfilePublisher": (".dense_v2", "CodeDenseProfilePublisher"),
    "CodeDensePublicationError": (".dense_v2", "CodeDensePublicationError"),
    "CodeDensePublicationResult": (".dense_v2", "CodeDensePublicationResult"),
    "CodeDenseRetriever": (".dense_v2", "CodeDenseRetriever"),
    "CodeDenseSearchResult": (".dense_v2", "CodeDenseSearchResult"),
    "CodeDenseStore": (".dense_v2", "CodeDenseStore"),
    "CodeDenseTrace": (".dense_v2", "CodeDenseTrace"),
    "CodeDenseUnavailableError": (".dense_v2", "CodeDenseUnavailableError"),
    "CodeHybridHitTrace": (".dense_v2", "CodeHybridHitTrace"),
    "CodeHybridSearchResult": (".dense_v2", "CodeHybridSearchResult"),
    "CodeHybridTrace": (".dense_v2", "CodeHybridTrace"),
    "CodeHybridV2Retriever": (".dense_v2", "CodeHybridV2Retriever"),
    "DEFAULT_CODE_NL_PROFILE": (".dense_v2", "DEFAULT_CODE_NL_PROFILE"),
    "DENSE_MODEL_CANDIDATES": (".dense_v2", "DENSE_MODEL_CANDIDATES"),
    "DenseModelCandidate": (".dense_v2", "DenseModelCandidate"),
    "resolve_code_embedding_profile": (
        ".dense_v2",
        "resolve_code_embedding_profile",
    ),
    "CodeDualWriteCoordinator": (".dual_write", "CodeDualWriteCoordinator"),
    "CodeDualWriteResult": (".dual_write", "CodeDualWriteResult"),
    "CodeDualWriteStore": (".dual_write", "CodeDualWriteStore"),
    "CodeEmbeddingError": (".embedding_v2", "CodeEmbeddingError"),
    "CodeEmbeddingIndexResult": (".embedding_v2", "CodeEmbeddingIndexResult"),
    "CodeEmbeddingIndexer": (".embedding_v2", "CodeEmbeddingIndexer"),
    "CodeEmbeddingStore": (".embedding_v2", "CodeEmbeddingStore"),
    "CodeEmbeddingTrace": (".embedding_v2", "CodeEmbeddingTrace"),
    "EmbeddingBatchError": (".embedding_v2", "EmbeddingBatchError"),
    "EmbeddingBatchResult": (".embedding_v2", "EmbeddingBatchResult"),
    "EmbeddingDimensionError": (".embedding_v2", "EmbeddingDimensionError"),
    "EmbeddingProfile": (".embedding_v2", "EmbeddingProfile"),
    "EmbeddingProvider": (".embedding_v2", "EmbeddingProvider"),
    "EmbeddingProviderUnavailableError": (
        ".embedding_v2",
        "EmbeddingProviderUnavailableError",
    ),
    "EmbeddingProvenance": (".embedding_v2", "EmbeddingProvenance"),
    "LocalHashCodeEmbeddingProvider": (
        ".embedding_v2",
        "LocalHashCodeEmbeddingProvider",
    ),
    "embedding_cache_key": (".embedding_v2", "embedding_cache_key"),
    "CodeGraphRetriever": (".graph_retrieval_v2", "CodeGraphRetriever"),
    "CodeGraphV2Retriever": (".graph_retrieval_v2", "CodeGraphV2Retriever"),
    "CodeTypedGraphRetriever": (".graph_retrieval_v2", "CodeTypedGraphRetriever"),
    "GraphAdjacencyProvider": (".graph_retrieval_v2", "GraphAdjacencyProvider"),
    "GraphEdge": (".graph_retrieval_v2", "GraphEdge"),
    "GraphNode": (".graph_retrieval_v2", "GraphNode"),
    "GraphPublication": (".graph_retrieval_v2", "GraphPublication"),
    "GraphTraversalCandidate": (".graph_retrieval_v2", "GraphTraversalCandidate"),
    "GraphTraversalPath": (".graph_retrieval_v2", "GraphTraversalPath"),
    "GraphTraversalRequest": (".graph_retrieval_v2", "GraphTraversalRequest"),
    "GraphTraversalResult": (".graph_retrieval_v2", "GraphTraversalResult"),
    "GraphTraversalStatus": (".graph_retrieval_v2", "GraphTraversalStatus"),
    "GraphTraversalTrace": (".graph_retrieval_v2", "GraphTraversalTrace"),
    "SQLiteGraphAdjacencyProvider": (
        ".graph_retrieval_v2",
        "SQLiteGraphAdjacencyProvider",
    ),
    "fuse_graph_candidates": (".graph_retrieval_v2", "fuse_graph_candidates"),
    "CODE_GRAPH_PUBLICATION_VERSION": (
        ".graph_publication_v2",
        "CODE_GRAPH_PUBLICATION_VERSION",
    ),
    "CodeGraphProfilePublisher": (
        ".graph_publication_v2",
        "CodeGraphProfilePublisher",
    ),
    "CodeGraphPublicationResult": (
        ".graph_publication_v2",
        "CodeGraphPublicationResult",
    ),
    "CodeGraphPublicationStore": (
        ".graph_publication_v2",
        "CodeGraphPublicationStore",
    ),
    "CodeChannelHitTrace": (".retrieval_v2", "CodeChannelHitTrace"),
    "CodeExactSparseRetriever": (".retrieval_v2", "CodeExactSparseRetriever"),
    "CodeExactSparseSearchResult": (".retrieval_v2", "CodeExactSparseSearchResult"),
    "CodeExactSparseTrace": (".retrieval_v2", "CodeExactSparseTrace"),
    "CodeLocatorKind": (".retrieval_v2", "CodeLocatorKind"),
    "CodeLocatorTrace": (".retrieval_v2", "CodeLocatorTrace"),
    "CodeV2RetrievalStore": (".retrieval_v2", "CodeV2RetrievalStore"),
    "CALIBRATION_ARTIFACT_VERSION": (
        ".rerank_v2",
        "CALIBRATION_ARTIFACT_VERSION",
    ),
    "DETERMINISTIC_RERANKER_VERSION": (
        ".rerank_v2",
        "DETERMINISTIC_RERANKER_VERSION",
    ),
    "RERANK_MODEL_CANDIDATES": (".rerank_v2", "RERANK_MODEL_CANDIDATES"),
    "RERANK_MODEL_VERSION": (".rerank_v2", "RERANK_MODEL_VERSION"),
    "CalibrationApplication": (".rerank_v2", "CalibrationApplication"),
    "CalibrationArtifact": (".rerank_v2", "CalibrationArtifact"),
    "CalibrationArtifactMismatchError": (
        ".rerank_v2",
        "CalibrationArtifactMismatchError",
    ),
    "CalibrationBin": (".rerank_v2", "CalibrationBin"),
    "CalibrationSample": (".rerank_v2", "CalibrationSample"),
    "CodeRerankTrace": (".rerank_v2", "CodeRerankTrace"),
    "CodeRerankedRetriever": (".rerank_v2", "CodeRerankedRetriever"),
    "CodeRerankedSearchResult": (".rerank_v2", "CodeRerankedSearchResult"),
    "DeterministicCodeReranker": (".rerank_v2", "DeterministicCodeReranker"),
    "EvidenceCard": (".rerank_v2", "EvidenceCard"),
    "FeatureVector": (".rerank_v2", "FeatureVector"),
    "RerankDeadlineExceeded": (".rerank_v2", "RerankDeadlineExceeded"),
    "RerankDecision": (".rerank_v2", "RerankDecision"),
    "RerankModelCandidate": (".rerank_v2", "RerankModelCandidate"),
    "apply_calibration": (".rerank_v2", "apply_calibration"),
    "fit_calibration": (".rerank_v2", "fit_calibration"),
    "CodeShadowError": (".shadow", "CodeShadowError"),
    "CodeShadowFailure": (".shadow", "CodeShadowFailure"),
    "CodeShadowObservation": (".shadow", "CodeShadowObservation"),
    "CodeShadowRankDelta": (".shadow", "CodeShadowRankDelta"),
    "CodeShadowRunner": (".shadow", "CodeShadowRunner"),
    "CodeShadowStage": (".shadow", "CodeShadowStage"),
    "CodeSourceRetrieverProtocol": (".shadow", "CodeSourceRetrieverProtocol"),
    "CodeSourceRetrieverV1Adapter": (".v1_adapter", "CodeSourceRetrieverV1Adapter"),
    "LegacyCodeResponseError": (".v1_adapter", "LegacyCodeResponseError"),
}


def __getattr__(name: str) -> Any:
    target = _LAZY_EXPORTS.get(name)
    if target is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    module_name, attribute = target
    value = getattr(import_module(module_name, __name__), attribute)
    globals()[name] = value
    return value


__all__ = [
    "CALIBRATION_ARTIFACT_VERSION",
    "CODE_EDGE_REGISTRY",
    "CODE_EDGE_SPECS",
    "CODE_QUERY_PROFILES",
    "CODE_QUERY_PROFILE_REGISTRY",
    "CODE_QUERY_PROFILE_REGISTRY_BY_KEY",
    "CODE_V2_SCHEMA",
    "DETERMINISTIC_RERANKER_VERSION",
    "EDGE_REGISTRY",
    "RERANK_MODEL_CANDIDATES",
    "RERANK_MODEL_VERSION",
    "CalibrationApplication",
    "CalibrationArtifact",
    "CalibrationArtifactMismatchError",
    "CalibrationBin",
    "CalibrationSample",
    "CodeAdaptiveK",
    "CodeCalibratedRelevance",
    "CodeCalibratedScore",
    "CodeCalibrationPolicy",
    "CodeCalibrationStatus",
    "CodeCandidateReranker",
    "CodeCandidateRole",
    "CodeChannelCompleteNoMatch",
    "CodeChannelCompletePruned",
    "CodeChannelCompleteWithHits",
    "CodeChannelDisabled",
    "CodeChannelError",
    "CodeChannelErrorKind",
    "CodeChannelFailure",
    "CodeChannelHitTrace",
    "CodeChannelOutcome",
    "CodeChannelOutcomeStatus",
    "CodeChannelRank",
    "CodeChannelScore",
    "CodeChannelTimeout",
    "CodeChannelUnavailable",
    "CodeContextBlock",
    "CodeContextTemplate",
    "CodeDerivation",
    "CodeDenseError",
    "CodeDenseHitTrace",
    "CodeDenseProfilePublisher",
    "CodeDensePublicationError",
    "CodeDensePublicationResult",
    "CodeDenseRetriever",
    "CodeDenseSearchResult",
    "CodeDenseStore",
    "CodeDenseTrace",
    "CodeDenseUnavailableError",
    "CodeDualWriteCoordinator",
    "CodeDualWriteResult",
    "CodeDualWriteStore",
    "CodeEmbeddingError",
    "CodeEmbeddingIndexResult",
    "CodeEmbeddingIndexer",
    "CodeEmbeddingStore",
    "CodeEmbeddingTrace",
    "CodeEdgeDerivationLayer",
    "CodeEdgeDirection",
    "CodeEdgeGenerationRequirement",
    "CodeEdgeInverse",
    "CodeEdgeOwner",
    "CodeEdgeReviewRequirement",
    "CodeEdgeSpec",
    "CodeEdgeVersionRequirement",
    "CodeExactSparseRetriever",
    "CodeExactSparseSearchResult",
    "CodeExactSparseTrace",
    "CodeFactStatus",
    "CodeFallback",
    "CodeFallbackFailure",
    "CodeFallbackFailed",
    "CodeFallbackNotUsed",
    "CodeFallbackStatus",
    "CodeFallbackSucceeded",
    "CodeHybridHitTrace",
    "CodeHybridSearchResult",
    "CodeHybridTrace",
    "CodeHybridV2Retriever",
    "CodeHistoryExpansionHook",
    "CodeGraphEntity",
    "CodeGraphEntityType",
    "CodeGraphProfilePublisher",
    "CodeGraphPublicationResult",
    "CodeGraphPublicationStore",
    "CodeGraphRetriever",
    "CodeGraphV2Retriever",
    "CodeTypedGraphRetriever",
    "CodeMissingRolePolicy",
    "CodeOptionalHookResult",
    "CodeOptionalHookStatus",
    "CodePipelineStageStatus",
    "CodePipelineTraceEvent",
    "CodeProfiledRetriever",
    "CodeQueryProfile",
    "CodeQueryProfileV2",
    "CodeQueryRewrite",
    "CodeRewritePolicy",
    "CodeRerankTrace",
    "CodeRerankedRetriever",
    "CodeRerankedSearchResult",
    "CodeRelationHop",
    "CodeRelationLocator",
    "CodeRelationNode",
    "CodeRelationPath",
    "CodeRelationType",
    "CodeLocatorKind",
    "CodeLocatorTrace",
    "CodeRetrievalBudget",
    "CodeRetrievalCandidate",
    "CodeRetrievalChannel",
    "CodeReviewStatus",
    "CodeShadowError",
    "CodeShadowFailure",
    "CodeShadowObservation",
    "CodeShadowRankDelta",
    "CodeShadowRunner",
    "CodeShadowStage",
    "CodeSourceError",
    "CodeSourceFusionPipeline",
    "CodeSourceFusionSearchResult",
    "CodeSourceFusionTrace",
    "CodeSourceResult",
    "CodeSourceRetrieverProtocol",
    "CodeSourceRetrieverV1Adapter",
    "CodeSourceStatus",
    "CodeSymbolKind",
    "CodeTask",
    "CodeTestValidationExpansionHook",
    "CodeTraversalDirection",
    "CodeUncalibratedScore",
    "CodeUnresolvedAggregate",
    "CodeUnresolvedDiagnostic",
    "CodeUnresolvedDiagnostics",
    "CodeUnresolvedLanguageModuleAggregate",
    "CodeUnresolvedReason",
    "CodeVersionAlignment",
    "CodeV2StoreMixin",
    "CodeV2RetrievalStore",
    "DEFAULT_CODE_NL_PROFILE",
    "CODE_GRAPH_PUBLICATION_VERSION",
    "DENSE_MODEL_CANDIDATES",
    "DenseModelCandidate",
    "DeterministicCodeReranker",
    "EmbeddingBatchError",
    "EmbeddingBatchResult",
    "EmbeddingDimensionError",
    "EmbeddingProfile",
    "EmbeddingProvider",
    "EmbeddingProviderUnavailableError",
    "EmbeddingProvenance",
    "EvidenceCard",
    "FeatureVector",
    "GraphAdjacencyProvider",
    "GraphEdge",
    "GraphNode",
    "GraphPublication",
    "GraphTraversalCandidate",
    "GraphTraversalPath",
    "GraphTraversalRequest",
    "GraphTraversalResult",
    "GraphTraversalStatus",
    "GraphTraversalTrace",
    "LegacyCodeResponseError",
    "LocalHashCodeEmbeddingProvider",
    "PIPELINE_VERSION",
    "PROFILE_REGISTRY_VERSION",
    "REWRITE_VERSION",
    "RerankDeadlineExceeded",
    "RerankDecision",
    "RerankModelCandidate",
    "ResolvedCodeQueryProfile",
    "SQLiteGraphAdjacencyProvider",
    "apply_calibration",
    "embedding_cache_key",
    "fit_calibration",
    "fuse_graph_candidates",
    "get_code_query_profile",
    "get_edge_spec",
    "registered_edge_type",
    "infer_code_task",
    "require_registered_edge_types",
    "resolve_code_query_profile",
    "resolve_code_embedding_profile",
    "rewrite_code_query",
    "summarize_unresolved_diagnostics",
    "validate_edge_assertion",
]

_SCIP_V1_EXPORTS = (
    "SCIP_CONSUMER_VERSION",
    "SafeScipRunner",
    "ScipBoundedArtifact",
    "ScipCommandExecutor",
    "ScipCommandPin",
    "ScipConsumeResult",
    "ScipConsumer",
    "ScipDecodeError",
    "ScipDecodeLimits",
    "ScipDecodedIndex",
    "ScipDiagnostic",
    "ScipDocument",
    "ScipEntityRef",
    "ScipExecutionOutcome",
    "ScipExecutionPolicy",
    "ScipFallbackTrace",
    "ScipLink",
    "ScipLinkedDocument",
    "ScipLinkedOccurrence",
    "ScipLinkedRelationship",
    "ScipLinkStatus",
    "ScipMetadata",
    "ScipNetworkIsolation",
    "ScipOccurrence",
    "ScipOccurrenceKind",
    "ScipPosition",
    "ScipProtobufDecoder",
    "ScipProvenance",
    "ScipRange",
    "ScipRawObject",
    "ScipReadOnlyResolver",
    "ScipIngestionResolver",
    "ScipRelationship",
    "ScipResolverFailure",
    "ScipRunnerResult",
    "ScipScope",
    "ScipStatus",
    "ScipSymbolInformation",
)
_LAZY_EXPORTS.update({name: (".scip_v1", name) for name in _SCIP_V1_EXPORTS})
__all__.extend(_SCIP_V1_EXPORTS)

_SEMANTIC_EDGES_V1_EXPORTS = (
    "DEFAULT_MIN_SEMANTIC_EDGE_CONFIDENCE",
    "DEFAULT_SEMANTIC_EDGE_SAMPLE_SIZE",
    "SCIP_EXPLICIT_CALL_ROLE",
    "SCIP_EXPLICIT_OVERRIDE_ROLE",
    "SEMANTIC_EDGE_LABEL_PROTOCOL_VERSION",
    "SEMANTIC_EDGE_TREATMENT_VERSION",
    "ConservativeSemanticEdge",
    "ScipSemanticRole",
    "SemanticEdge",
    "SemanticEdgeConflict",
    "SemanticEdgeDiagnostic",
    "SemanticEdgeDiagnosticCode",
    "SemanticEdgeDiagnosticCount",
    "SemanticEdgeDiagnosticSeverity",
    "SemanticEdgeEndpoint",
    "SemanticEdgeEvaluation",
    "SemanticEdgeEvaluationStatus",
    "SemanticEdgeFallbackTrace",
    "SemanticEdgePrecisionLabel",
    "SemanticEdgePrecisionVerdict",
    "SemanticEdgeProvenance",
    "SemanticEdgeQualityMetrics",
    "SemanticEdgeScope",
    "SemanticEdgeStructuralCounts",
    "SemanticEdgeSupportStatus",
    "SemanticEdgeTreatment",
    "SemanticEdgeTreatmentResult",
    "SemanticEdgeTreatmentStatus",
    "SemanticScipStatus",
    "TreeSitterConservativeEdge",
    "evaluate_semantic_edges",
    "sample_semantic_edges",
    "treat_python_semantic_edges",
)
_LAZY_EXPORTS.update({name: (".semantic_edges_v1", name) for name in _SEMANTIC_EDGES_V1_EXPORTS})
__all__.extend(_SEMANTIC_EDGES_V1_EXPORTS)

_HISTORY_V2_EXPORTS = (
    "DEFAULT_HISTORY_PROFILE",
    "HISTORY_CONTRACT_VERSION",
    "HISTORY_SCHEMA_VERSION",
    "LINEAGE_CONTRACT_VERSION",
    "GitRenameHint",
    "HistoricalFile",
    "HistoricalFileStatus",
    "HistoricalMaterializer",
    "HistoricalPublicationStore",
    "HistoricalUnit",
    "CodeHistoryDiffExpansionHook",
    "CodeHistoryHookStore",
    "HistoryDiagnostic",
    "HistoryDiagnosticCode",
    "HistoryDiagnosticSeverity",
    "HistoryError",
    "HistoryEvictionResult",
    "HistoryGitError",
    "HistoryMaterializationPolicy",
    "HistoryMaterializationRequest",
    "HistoryMaterializationSelection",
    "HistoryMaterializationStatus",
    "HistoryMaterializer",
    "HistoryNamespace",
    "HistoryNamespaceKind",
    "HistoryPinReason",
    "HistoryProvenance",
    "HistoryPublication",
    "HistoryPublicationError",
    "HistoryScopeError",
    "HistoryStatus",
    "HistoryTrace",
    "InMemoryHistoricalPublicationStore",
    "LineageCandidate",
    "LineageDiagnostic",
    "LineageDiagnosticCode",
    "LineageRelationType",
    "LineageSignal",
    "LineageStatus",
    "SQLiteHistoricalPublicationStore",
    "SymbolLineage",
    "SymbolLineageRequest",
    "SymbolLineageResolver",
    "SymbolLineageResult",
    "SymbolLineageTrace",
    "history_content_key",
)
_LAZY_EXPORTS.update({name: (".history_v2", name) for name in _HISTORY_V2_EXPORTS})
__all__.extend(_HISTORY_V2_EXPORTS)

_DIFF_SYMBOL_V2_EXPORTS = (
    "DIFF_SYMBOL_CONTRACT_VERSION",
    "DIFF_SYMBOL_EVALUATION_VERSION",
    "DIFF_SYMBOL_MAPPER_VERSION",
    "DiffChangeType",
    "DiffHunkProvenance",
    "DiffHunkVersion",
    "DiffSymbolDiagnostic",
    "DiffSymbolDiagnosticCode",
    "DiffSymbolDiagnosticSeverity",
    "DiffSymbolEdge",
    "DiffSymbolError",
    "DiffSymbolEvaluation",
    "DiffSymbolEvaluationLabel",
    "DiffSymbolMapper",
    "DiffSymbolMatch",
    "DiffSymbolMatchKind",
    "DiffSymbolMatchStatus",
    "DiffSymbolScopeError",
    "DiffSymbolSide",
    "DiffSymbolSignal",
    "DiffSymbolTrace",
    "DiffSymbolTreatment",
    "DiffSymbolTreatmentStatus",
    "SymbolVersionRef",
)
_LAZY_EXPORTS.update({name: (".diff_symbol_v2", name) for name in _DIFF_SYMBOL_V2_EXPORTS})
__all__.extend(_DIFF_SYMBOL_V2_EXPORTS)

_TEST_VALIDATION_V2_EXPORTS = (
    "TEST_VALIDATION_BINDER_VERSION",
    "TEST_VALIDATION_CONTRACT_VERSION",
    "CoverageEvidence",
    "CodeTestValidationExpansionHookV2",
    "CodeTestValidationHookStore",
    "RawObjectRef",
    "TestExecutionStatus",
    "TestObservation",
    "TestResultV2",
    "TestStatusConsistency",
    "TestSymbolBinding",
    "TestSymbolBindingStatus",
    "TestSymbolEvidence",
    "TestSymbolSignal",
    "TestSymbolVersion",
    "TestTargetVersion",
    "TestValidationBinder",
    "TestValidationEdge",
    "TestValidationEdgeRole",
    "TestValidationError",
    "TestValidationMapper",
    "TestValidationScopeError",
    "TestValidationTrace",
    "ValidationDiagnostic",
    "ValidationDiagnosticCode",
    "ValidationDiagnosticSeverity",
    "ValidationTreatment",
    "ValidationTreatmentStatus",
)
_LAZY_EXPORTS.update({name: (".test_validation_v2", name) for name in _TEST_VALIDATION_V2_EXPORTS})
__all__.extend(_TEST_VALIDATION_V2_EXPORTS)

_CONTEXT_BUILDER_V2_EXPORTS = (
    "CODE_TASK_CONTEXT_ROLE_ORDER",
    "CONTEXT_BUILDER_CONTRACT_VERSION",
    "CONTEXT_BUILDER_VERSION",
    "CodeTaskContextBuild",
    "CodeTaskContextBuilder",
    "ComprehensionContext",
    "ContextBudget",
    "ContextBudgetTrace",
    "ContextBuildError",
    "ContextBuildLocatorError",
    "ContextBuildRefusalError",
    "ContextBuildScope",
    "ContextBuildScopeError",
    "ContextBuildStatus",
    "ContextBuildTrace",
    "ContextCitation",
    "ContextMetric",
    "ContextMetricStatus",
    "ContextMissingRole",
    "ContextMissingStatus",
    "ContextRefusal",
    "ContextRefusalCode",
    "ContextRole",
    "ContextRoleBlock",
    "ContextVersion",
    "RetrievalContext",
    "RetrievalContextCandidate",
)
_LAZY_EXPORTS.update({name: (".context_builder_v2", name) for name in _CONTEXT_BUILDER_V2_EXPORTS})
__all__.extend(_CONTEXT_BUILDER_V2_EXPORTS)

_SOURCE_SCOPE_ATTESTATION_EXPORTS = (
    "SOURCE_SCOPE_ATTESTATION_VERSION",
    "CodeSourceBlockPublicationIdentity",
    "CodeSourceScopeAttestation",
    "CodeSourceScopeAttestationError",
)
_LAZY_EXPORTS.update(
    {name: (".query_profile_v2", name) for name in _SOURCE_SCOPE_ATTESTATION_EXPORTS}
)
__all__.extend(_SOURCE_SCOPE_ATTESTATION_EXPORTS)

_PLATFORM_V2_EXPORTS = (
    "CODE_ENGINE_HEADER",
    "CODE_PLATFORM_INTEGRATION_VERSION",
    "CodeEngineOverrideError",
    "CodePlatformIntegration",
)
_LAZY_EXPORTS.update({name: (".platform_v2", name) for name in _PLATFORM_V2_EXPORTS})
__all__.extend(_PLATFORM_V2_EXPORTS)

_RELEASE_V2_EXPORTS = (
    "ARTIFACT_ORDER",
    "CB0_QUALIFIED_RUN_ID",
    "CB6_PROVISIONAL_RUN_ID",
    "COST_EVIDENCE_VERSION",
    "DEFAULT_RUNTIME_ENGINE",
    "GATE_REQUIREMENTS",
    "GATE_REQUIREMENT_BY_NAME",
    "GUARDRAIL_ORDER",
    "LATENCY_EVIDENCE_VERSION",
    "MAX_EVIDENCE_AGE_SECONDS",
    "MAX_SHADOW_BATCHES",
    "MAX_SHADOW_SAMPLES",
    "MINIMUM_STAGE_SAMPLES",
    "RELEASE_ARTIFACT_VERSION",
    "RELEASE_ATTESTATION_VERSION",
    "RELEASE_CONTRACT_VERSION",
    "RELEASE_DECISION_VERSION",
    "RELEASE_EVALUATOR_VERSION",
    "RELEASE_EVIDENCE_VERSION",
    "RELEASE_GUARDRAIL_VERSION",
    "RELEASE_METRIC_VERSION",
    "RELEASE_POLICY_VERSION",
    "RELEASE_SOURCE_VERSION",
    "RELEASE_STAGE_ORDER",
    "REQUIRED_ARTIFACT_DISPOSITION",
    "ROLLBACK_ACTIONS",
    "ROLLBACK_PLAN_VERSION",
    "SHADOW_AGGREGATE_VERSION",
    "ArtifactDisposition",
    "ArtifactVersionExpectation",
    "EvidenceAttestation",
    "EvidenceClass",
    "EvidenceSource",
    "EvidenceStatus",
    "EvidenceVerifier",
    "GateRequirement",
    "GuardrailName",
    "GuardrailStatus",
    "MetricUnit",
    "ReleaseArtifact",
    "ReleaseArtifactKind",
    "ReleaseCostEvidence",
    "ReleaseDecision",
    "ReleaseDecisionStatus",
    "ReleaseEvidence",
    "ReleaseGuardrail",
    "ReleaseLatencyEvidence",
    "ReleaseMetric",
    "ReleaseMetricName",
    "ReleasePolicy",
    "ReleaseStage",
    "ReleaseVersions",
    "RollbackAction",
    "RollbackPlan",
    "SanitizedShadowCounters",
    "ShadowEvidenceAggregate",
    "ShadowRate",
    "TestHMACSHA256Verifier",
    "ThresholdOperator",
    "aggregate_shadow_evidence",
    "create_test_attestation",
    "current_release_evidence",
    "evaluate_release",
)
_LAZY_EXPORTS.update({name: (".release_v2", name) for name in _RELEASE_V2_EXPORTS})
__all__.extend(_RELEASE_V2_EXPORTS)

_RAW_GATEWAY_V2_EXPORTS = (
    "CODE_RAW_GATEWAY_V2_VERSION",
    "CodeRawBindingRequestV2",
    "CodeRawGatewayV2",
    "CodeRawReadRequestV2",
)
_LAZY_EXPORTS.update({name: (".raw_gateway_v2", name) for name in _RAW_GATEWAY_V2_EXPORTS})
__all__.extend(_RAW_GATEWAY_V2_EXPORTS)
