"""Notebook Source V2 contracts, adapter, and isolated persistence."""

from . import contracts as _contracts
from .adapter_v2 import (
    MAX_CELLS,
    MAX_NOTEBOOK_BYTES,
    MAX_OUTPUTS_PER_CELL,
    NotebookAdapterError,
    NotebookAdapterV2,
)
from .baseline_v1 import (
    NOTEBOOK_BASELINE_ARTIFACT_FILES,
    NOTEBOOK_BASELINE_ARTIFACT_VERSION,
    NOTEBOOK_BASELINE_SEED,
    NOTEBOOK_BASELINE_VERIFY_VERSION,
    NOTEBOOK_BASELINE_VERSION,
    NotebookBaselineVerification,
    run_notebook_baseline_v1,
    verify_notebook_baseline_artifact_v1,
)
from .cell_matcher import (
    NOTEBOOK_CELL_MATCHER_VERSION,
    NOTEBOOK_COMPARISON_SELECTION_VERSION,
    NotebookCellChangeType,
    NotebookCellMatch,
    NotebookCellMatchMethod,
    NotebookComparisonResult,
    NotebookComparisonSelectionError,
    NotebookComparisonSelectionTraceV2,
    NotebookComparisonSpecV2,
    NotebookParameterChange,
    NotebookPublicationSelectorV2,
    compare_notebook_publications_v2,
    select_notebook_comparison_v2,
)
from .code_analyzer import (
    NOTEBOOK_CODE_ANALYZER_VERSION,
    NotebookCodeAnalysis,
    analyze_notebook_code_v2,
)
from .context import build_notebook_context_from_search_v2
from .context_builder import (
    NOTEBOOK_CONTEXT_BUILDER_VERSION,
    NotebookContextAvailability,
    NotebookContextBlock,
    NotebookContextBuilderV2,
    NotebookContextBundle,
    NotebookContextCitation,
    NotebookContextMetrics,
)
from .contracts import __all__ as _contracts_all
from .dependency_graph import (
    NOTEBOOK_DEPENDENCY_GRAPH_VERSION,
    build_notebook_dependency_graph_v2,
    build_notebook_structural_edges_v2,
)
from .evaluation_v1 import (
    EXPECTED_NOTEBOOK_SLICE_COUNTS,
    NOTEBOOK_GOLDEN_AUTHORITY_SHA256,
    NOTEBOOK_GOLDEN_CASE_COUNT,
    NOTEBOOK_GOLDEN_PACKAGE_SHA256,
    NotebookEvaluationReport,
    NotebookFoundationProbe,
    NotebookGoldenCase,
    NotebookGoldenDataset,
    NotebookGoldenError,
    NotebookGoldenSlice,
    NotebookMetric,
    NotebookMetricResult,
    NotebookMetricStatus,
    NotebookReviewAvailability,
    NotebookReviewedCandidate,
    NotebookReviewedRow,
    NotebookSliceResult,
    evaluate_reviewed_notebook_retrieval,
    load_notebook_golden_v1,
    perfect_reviewed_rows_v1,
    probe_notebook_foundation_v1,
)
from .execution_state import (
    NOTEBOOK_EXECUTION_STATE_VERSION,
    NotebookCellExecutionInput,
    NotebookCellExecutionProjection,
    project_notebook_execution_state_v2,
)
from .fixture_v1 import (
    NOTEBOOK_FIXTURE_RECIPE_VERSION,
    NOTEBOOK_GOLDEN_ACL_REF,
    NOTEBOOK_GOLDEN_DATASET_ID,
    NOTEBOOK_GOLDEN_DATASET_VERSION,
    NOTEBOOK_GOLDEN_GENERATION_ID,
    NOTEBOOK_GOLDEN_PROJECT_ID,
    NotebookFixtureAlias,
    NotebookFixtureBundle,
    NotebookFixtureEntity,
    build_notebook_fixture_v1,
)
from .output_parser import (
    NOTEBOOK_OUTPUT_PARSER_VERSION,
    ParsedNotebookOutput,
    parse_notebook_output_v2,
    sanitize_notebook_derived_text_v2,
)
from .parameter_parser import (
    NOTEBOOK_PARAMETER_PARSER_VERSION,
    NotebookParameterParseResult,
    ParsedNotebookParameter,
    parse_notebook_parameters_v2,
)
from .release_v2 import (
    NOTEBOOK_RELEASE_EVALUATOR_VERSION,
    NOTEBOOK_RELEASE_THRESHOLDS,
    NOTEBOOK_REQUIRED_GUARDRAILS,
    NotebookEvidenceStatus,
    NotebookReleaseDecision,
    NotebookReleaseDecisionType,
    NotebookReleaseEvidence,
    NotebookReleaseGuardrail,
    NotebookReleaseMetric,
    NotebookReleaseStage,
    build_notebook_release_evidence_v2,
    evaluate_notebook_release_v2,
)
from .reranker import (
    NOTEBOOK_RERANKER_VERSION,
    NotebookRerankFeatures,
    NotebookRerankResult,
    rerank_notebook_candidate_v2,
)
from .retriever import (
    NOTEBOOK_RETRIEVER_VERSION,
    NotebookCandidate,
    NotebookChannel,
    NotebookChannelTrace,
    NotebookFilterError,
    NotebookFilterSelectionTraceV2,
    NotebookQueryProfile,
    NotebookQueryTask,
    NotebookRetrieverV2,
    NotebookSearchFiltersV2,
    NotebookSearchResult,
    NotebookSearchScope,
    NotebookSearchTrace,
    filter_notebook_publications_v2,
    profile_notebook_query_v2,
)
from .runtime_v2 import (
    NOTEBOOK_SOURCE_DEFAULT_ENGINE,
    NOTEBOOK_SOURCE_RUNTIME_VERSION,
    NotebookSourceRuntimeError,
    NotebookSourceRuntimeV2,
)
from .schema import NOTEBOOK_V2_SCHEMA, NOTEBOOK_V2_TABLES
from .store import (
    NotebookPublicationError,
    NotebookStoreError,
    NotebookStorePathError,
    NotebookV2Store,
)
from .unit_builder import (
    NOTEBOOK_UNIT_BUILDER_VERSION,
    build_notebook_retrieval_units_v2,
)

for _name in _contracts_all:
    globals()[_name] = getattr(_contracts, _name)

__all__ = [
    *_contracts_all,
    "MAX_CELLS",
    "MAX_NOTEBOOK_BYTES",
    "MAX_OUTPUTS_PER_CELL",
    "NOTEBOOK_BASELINE_ARTIFACT_FILES",
    "NOTEBOOK_BASELINE_ARTIFACT_VERSION",
    "NOTEBOOK_BASELINE_SEED",
    "NOTEBOOK_BASELINE_VERIFY_VERSION",
    "NOTEBOOK_BASELINE_VERSION",
    "NOTEBOOK_CODE_ANALYZER_VERSION",
    "NOTEBOOK_CELL_MATCHER_VERSION",
    "NOTEBOOK_COMPARISON_SELECTION_VERSION",
    "NOTEBOOK_CONTEXT_BUILDER_VERSION",
    "NOTEBOOK_DEPENDENCY_GRAPH_VERSION",
    "NOTEBOOK_EXECUTION_STATE_VERSION",
    "NOTEBOOK_V2_SCHEMA",
    "NOTEBOOK_V2_TABLES",
    "NOTEBOOK_OUTPUT_PARSER_VERSION",
    "NOTEBOOK_PARAMETER_PARSER_VERSION",
    "NOTEBOOK_RELEASE_EVALUATOR_VERSION",
    "NOTEBOOK_RELEASE_THRESHOLDS",
    "NOTEBOOK_REQUIRED_GUARDRAILS",
    "NOTEBOOK_RERANKER_VERSION",
    "NOTEBOOK_SOURCE_DEFAULT_ENGINE",
    "NOTEBOOK_SOURCE_RUNTIME_VERSION",
    "NOTEBOOK_RETRIEVER_VERSION",
    "NOTEBOOK_UNIT_BUILDER_VERSION",
    "NOTEBOOK_FIXTURE_RECIPE_VERSION",
    "EXPECTED_NOTEBOOK_SLICE_COUNTS",
    "NOTEBOOK_GOLDEN_AUTHORITY_SHA256",
    "NOTEBOOK_GOLDEN_ACL_REF",
    "NOTEBOOK_GOLDEN_CASE_COUNT",
    "NOTEBOOK_GOLDEN_DATASET_ID",
    "NOTEBOOK_GOLDEN_DATASET_VERSION",
    "NOTEBOOK_GOLDEN_GENERATION_ID",
    "NOTEBOOK_GOLDEN_PACKAGE_SHA256",
    "NOTEBOOK_GOLDEN_PROJECT_ID",
    "NotebookAdapterError",
    "NotebookAdapterV2",
    "NotebookBaselineVerification",
    "NotebookCellExecutionInput",
    "NotebookCellExecutionProjection",
    "NotebookCellChangeType",
    "NotebookCellMatch",
    "NotebookCellMatchMethod",
    "NotebookCodeAnalysis",
    "NotebookComparisonResult",
    "NotebookComparisonSelectionError",
    "NotebookComparisonSelectionTraceV2",
    "NotebookComparisonSpecV2",
    "NotebookContextAvailability",
    "NotebookContextBlock",
    "NotebookContextBuilderV2",
    "NotebookContextBundle",
    "NotebookContextCitation",
    "NotebookContextMetrics",
    "NotebookEvaluationReport",
    "NotebookEvidenceStatus",
    "NotebookFixtureAlias",
    "NotebookFixtureBundle",
    "NotebookFixtureEntity",
    "NotebookFilterError",
    "NotebookFilterSelectionTraceV2",
    "NotebookFoundationProbe",
    "NotebookGoldenCase",
    "NotebookGoldenDataset",
    "NotebookGoldenError",
    "NotebookGoldenSlice",
    "NotebookMetric",
    "NotebookMetricResult",
    "NotebookMetricStatus",
    "NotebookParameterParseResult",
    "NotebookParameterChange",
    "NotebookPublicationError",
    "NotebookPublicationSelectorV2",
    "NotebookQueryProfile",
    "NotebookQueryTask",
    "NotebookCandidate",
    "NotebookChannel",
    "NotebookChannelTrace",
    "NotebookRerankFeatures",
    "NotebookRerankResult",
    "NotebookReleaseDecision",
    "NotebookReleaseDecisionType",
    "NotebookReleaseEvidence",
    "NotebookReleaseGuardrail",
    "NotebookReleaseMetric",
    "NotebookReleaseStage",
    "NotebookRetrieverV2",
    "NotebookReviewAvailability",
    "NotebookReviewedCandidate",
    "NotebookReviewedRow",
    "NotebookSliceResult",
    "NotebookSearchResult",
    "NotebookSearchFiltersV2",
    "NotebookSearchScope",
    "NotebookSearchTrace",
    "NotebookStoreError",
    "NotebookStorePathError",
    "NotebookSourceRuntimeError",
    "NotebookSourceRuntimeV2",
    "NotebookV2Store",
    "ParsedNotebookOutput",
    "ParsedNotebookParameter",
    "analyze_notebook_code_v2",
    "build_notebook_fixture_v1",
    "build_notebook_context_from_search_v2",
    "build_notebook_dependency_graph_v2",
    "build_notebook_release_evidence_v2",
    "build_notebook_structural_edges_v2",
    "build_notebook_retrieval_units_v2",
    "compare_notebook_publications_v2",
    "filter_notebook_publications_v2",
    "evaluate_reviewed_notebook_retrieval",
    "evaluate_notebook_release_v2",
    "load_notebook_golden_v1",
    "perfect_reviewed_rows_v1",
    "parse_notebook_output_v2",
    "parse_notebook_parameters_v2",
    "probe_notebook_foundation_v1",
    "project_notebook_execution_state_v2",
    "profile_notebook_query_v2",
    "select_notebook_comparison_v2",
    "rerank_notebook_candidate_v2",
    "run_notebook_baseline_v1",
    "sanitize_notebook_derived_text_v2",
    "verify_notebook_baseline_artifact_v1",
]

del _name
